services:
  airflow:
    image: apache/airflow:2.9.3
    container_name: airflow-gpi
    env_file:
      - setup.env
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW_DATA_DIR: /opt/airflow/data

      # Use Postgres for Airflow metadata DB (important)
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://gpi:gpi@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./secrets:/opt/airflow/secrets:ro
    ports:
      - "8080:8080"
    command: >
      bash -lc "
      pip install kaggle pandas psycopg2-binary &&
      airflow db migrate &&
      airflow users create -r Admin -u admin -p admin -e admin@example.com -f Admin -l User || true &&
      airflow webserver --port 8080 -D &&
      exec airflow scheduler
      "
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: gpi-postgres
    environment:
      POSTGRES_USER: gpi
      POSTGRES_PASSWORD: gpi
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: gpi-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  pgdata: